#!/bin/sh

GUNICORN=/home/wwwpub/.virtualenvs/defaultproject/bin/gunicorn_django
ROOT=/opt/www/thumbtack
PID=/var/run/defaultproject.pid

if [ -f $PID ]
    then rm $PID
fi

cd $ROOT
exec $GUNICORN -c $ROOT/gunicorn.conf.py --pid=$PID